# Generated by Django 5.1.4 on 2026-08-16 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('login_at', models.DateTimeField(verbose_name='login at')),
                ('logout_at', models.DateTimeField(blank=True, null=True, verbose_name='logout at')),
                ('state', models.CharField(choices=[('WORKING', 'Working'), ('ON_BREAK', 'On Break'), ('OFFLINE', 'Offline')], db_index=True, default='WORKING', max_length=10, verbose_name='state')),
                ('last_heartbeat_at', models.DateTimeField(verbose_name='last heartbeat at')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='The user who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='The user who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'attendance session',
                'verbose_name_plural': 'attendance sessions',
                'ordering': ['-login_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('shift_duration_minutes', models.PositiveIntegerField(default=540, help_text='Standard shift length — 540 = 9 hours.', verbose_name='shift duration (minutes)')),
                ('shift_start_time', models.TimeField(blank=True, null=True, verbose_name='shift start time')),
                ('shift_end_time', models.TimeField(blank=True, null=True, verbose_name='shift end time')),
                ('allowed_break_minutes', models.PositiveIntegerField(default=60, verbose_name='allowed break (minutes)')),
                ('idle_timeout_minutes', models.PositiveIntegerField(default=5, help_text='No heartbeat for longer than this closes the current WORK segment and opens an IDLE one.', verbose_name='idle timeout (minutes)')),
                ('overtime_threshold_minutes', models.PositiveIntegerField(default=0, help_text='Active minutes beyond shift_duration_minutes + this threshold count as overtime.', verbose_name='overtime threshold (minutes)')),
                ('is_salary_enabled', models.BooleanField(default=False, verbose_name='salary calculation enabled')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='hourly rate')),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=1.5, help_text='Overtime hours are paid at hourly_rate * this multiplier.', max_digits=4, verbose_name='overtime multiplier')),
                ('currency', models.CharField(default='USD', max_length=8, verbose_name='currency')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='The user who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='The user who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'shift configuration',
                'verbose_name_plural': 'shift configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('segment_type', models.CharField(choices=[('WORK', 'Work'), ('BREAK', 'Break'), ('IDLE', 'Idle')], db_index=True, max_length=8, verbose_name='type')),
                ('started_at', models.DateTimeField(verbose_name='started at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='ended at')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='The user who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='attendance.attendancesession', verbose_name='session')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='The user who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'time segment',
                'verbose_name_plural': 'time segments',
                'ordering': ['session', 'started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['employee', 'login_at'], name='attend_sess_emp_login_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['employee', 'logout_at'], name='attend_sess_emp_logout_idx'),
        ),
        migrations.AddIndex(
            model_name='timesegment',
            index=models.Index(fields=['session', 'segment_type'], name='attendance_segment_type_idx'),
        ),
    ]
