"""Root URL configuration for the Qualify Learn CRM backend.

CP1 exposes only infrastructure endpoints:

* ``GET /health``       — simple, public liveness probe (no DB access yet).
* ``GET /api/schema/``  — OpenAPI 3 schema generated by drf-spectacular.
* ``GET /api/docs/``    — Swagger UI rendering that schema.

Domain routes are mounted under the versioned ``/api/v1/`` prefix in later
checkpoints as apps are introduced.
"""
from django.contrib import admin
from django.http import JsonResponse
from django.urls import path

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView


def health(request):
    """Public liveness probe.

    Intentionally does NOT touch the database — it only confirms the WSGI/ASGI
    application is up and able to serve a request. A DB-aware readiness check
    can be added later if deployment needs it.
    """
    return JsonResponse({"status": "healthy", "service": "crm-backend"})


urlpatterns = [
    path("admin/", admin.site.urls),
    # Infrastructure endpoints
    path("health", health, name="health"),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
]
