"""Root URL configuration for the Qualify Learn CRM backend.

Infrastructure endpoints (CP1, plus /ready from the final production
infrastructure pass):

* ``GET /health``       — simple, public liveness probe (no DB access yet).
* ``GET /ready``        — readiness probe: verifies the database is
  actually reachable, for a load balancer/orchestrator to use before
  routing real traffic to an instance (a process can be "alive" per
  ``/health`` while still unable to serve a single real request if its
  DB connection is down).
* ``GET /api/schema/``  — OpenAPI 3 schema generated by drf-spectacular.
* ``GET /api/docs/``    — Swagger UI rendering that schema.

Final internet-facing security audit: ``/api/schema/``/``/api/docs/``
publish the entire API surface (every endpoint, every field name) to
whoever requests them — reconnaissance value for an attacker with no
corresponding benefit for an internal-tool CRM with no third-party API
consumers. Public in development (``settings.API_DOCS_PUBLIC``, True by
default there) for day-to-day usability; requires authentication in
production, where that setting defaults False — see
``config/settings/production.py``.

Domain routes are mounted under the versioned ``/api/v1/`` prefix as apps
introduce them. CP3 adds the first one: ``/api/v1/auth/`` (login, refresh,
logout, current-user — see apps/accounts/urls.py).
"""
from django.conf import settings
from django.contrib import admin
from django.core.cache import cache
from django.db import DatabaseError, connections
from django.db.utils import OperationalError
from django.http import JsonResponse
from django.urls import include, path
from rest_framework.permissions import IsAuthenticated

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

from apps.communications.views import A1RoutesWebhookView, InboundEmailWebhookView, WhatsAppWebhookView


def health(request):
    """Public liveness probe.

    Intentionally does NOT touch the database — it only confirms the WSGI/ASGI
    application is up and able to serve a request. A DB-aware readiness check
    can be added later if deployment needs it.
    """
    return JsonResponse({"status": "healthy", "service": "crm-backend"})


def ready(request):
    """Readiness probe: actually opens a database connection and runs a
    trivial query, then does the same for the cache (Redis in
    production, LocMemCache in development — either way, a real
    round-trip, not a repeat of ``health``'s "the process is up" claim).
    Returns 503 (not 200) if either dependency is unreachable, so a load
    balancer/orchestrator can correctly stop routing traffic to this
    instance instead of serving 500s to real users. No response body
    ever includes connection details/secrets — only which dependency
    failed, never why (the exception itself, which could echo connection
    details, is never included).
    """
    try:
        with connections["default"].cursor() as cursor:
            cursor.execute("SELECT 1")
    except (DatabaseError, OperationalError):
        return JsonResponse({"status": "unavailable", "dependency": "database", "service": "crm-backend"}, status=503)

    try:
        cache.set("readiness-probe", "1", timeout=5)
        cache.get("readiness-probe")
    except Exception:  # noqa: BLE001 - any cache backend failure means "not ready", full stop
        return JsonResponse({"status": "unavailable", "dependency": "cache", "service": "crm-backend"}, status=503)

    return JsonResponse({"status": "ready", "service": "crm-backend"})


_docs_permission_classes = [] if getattr(settings, "API_DOCS_PUBLIC", True) else [IsAuthenticated]

urlpatterns = [
    path("admin/", admin.site.urls),
    # Infrastructure endpoints
    path("health", health, name="health"),
    path("ready", ready, name="ready"),
    path(
        "api/schema/",
        SpectacularAPIView.as_view(permission_classes=_docs_permission_classes),
        name="schema",
    ),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="schema", permission_classes=_docs_permission_classes),
        name="swagger-ui",
    ),
    # Domain APIs, versioned under /api/v1/
    path("api/v1/auth/", include("apps.accounts.urls")),
    path("api/v1/crm/", include("apps.crm.urls")),
    path("api/v1/organization/", include("apps.organization.urls")),
    path("api/v1/sales/", include("apps.sales.urls")),
    path("api/v1/catalog/", include("apps.catalog.urls")),
    path("api/v1/activities/", include("apps.activities.urls")),
    path("api/v1/communications/", include("apps.communications.urls")),
    path("api/v1/reports/", include("apps.reports.urls")),
    path("api/v1/workflows/", include("apps.workflows.urls")),
    path("api/v1/integrations/", include("apps.integrations.urls")),
    path("api/v1/system/", include("apps.system.urls")),
    path("api/v1/attendance/", include("apps.attendance.urls")),
    # Inbound provider webhooks — deliberately NOT under /api/v1/communications/:
    # these are unauthenticated-by-JWT (the provider has no user account),
    # authenticated instead by their own signature scheme (see
    # apps.communications.views.A1RoutesWebhookView/WhatsAppWebhookView).
    # A distinct top-level prefix keeps that trust boundary visually
    # obvious in the URL itself, not just in a comment.
    path("api/v1/webhooks/a1routes/", A1RoutesWebhookView.as_view(), name="webhook-a1routes"),
    path("api/v1/webhooks/whatsapp/", WhatsAppWebhookView.as_view(), name="webhook-whatsapp"),
    path("api/v1/webhooks/inbound-email/", InboundEmailWebhookView.as_view(), name="webhook-inbound-email"),
]
