"""Root URL configuration for the Qualify Learn CRM backend.

Infrastructure endpoints (CP1):

* ``GET /health``       — simple, public liveness probe (no DB access yet).
* ``GET /api/schema/``  — OpenAPI 3 schema generated by drf-spectacular.
* ``GET /api/docs/``    — Swagger UI rendering that schema.

Domain routes are mounted under the versioned ``/api/v1/`` prefix as apps
introduce them. CP3 adds the first one: ``/api/v1/auth/`` (login, refresh,
logout, current-user — see apps/accounts/urls.py).
"""
from django.contrib import admin
from django.http import JsonResponse
from django.urls import include, path

from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView


def health(request):
    """Public liveness probe.

    Intentionally does NOT touch the database — it only confirms the WSGI/ASGI
    application is up and able to serve a request. A DB-aware readiness check
    can be added later if deployment needs it.
    """
    return JsonResponse({"status": "healthy", "service": "crm-backend"})


urlpatterns = [
    path("admin/", admin.site.urls),
    # Infrastructure endpoints
    path("health", health, name="health"),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    # Domain APIs, versioned under /api/v1/
    path("api/v1/auth/", include("apps.accounts.urls")),
]
