# Generated by Django 5.1.4 on 2026-08-06 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Business-status flag (e.g. paused automation), independent of soft delete.', verbose_name='is active')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='The user who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_workflows', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='The user who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'workflow',
                'verbose_name_plural': 'workflows',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('action_type', models.CharField(choices=[('SEND_EMAIL', 'Send Email'), ('CREATE_TASK', 'Create Task'), ('CREATE_NOTIFICATION', 'Create Notification'), ('LOG_ACTIVITY', 'Log Activity')], db_index=True, max_length=20, verbose_name='action type')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text="Action-type-specific parameters — interpreted by services.py's dispatch table.", verbose_name='configuration')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='The user who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='The user who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflows.workflow', verbose_name='workflow')),
            ],
            options={
                'verbose_name': 'workflow action',
                'verbose_name_plural': 'workflow actions',
                'ordering': ['workflow', 'position'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('trigger_type', models.CharField(choices=[('ON_CREATE', 'On Create'), ('ON_UPDATE', 'On Update'), ('ON_DELETE', 'On Delete'), ('MANUAL', 'Manual')], db_index=True, default='MANUAL', max_length=10, verbose_name='trigger type')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text="A simple {'field': ..., 'equals': ...} check against the entity — see services.evaluate_conditions(). Empty means 'always match'.", verbose_name='conditions')),
                ('content_type', models.ForeignKey(blank=True, help_text="Which CRM entity type this trigger watches — e.g. 'any Lead'. Null for a type-agnostic MANUAL trigger.", limit_choices_to=models.Q(models.Q(('app_label', 'crm'), ('model__in', ['customer', 'lead', 'opportunity'])), models.Q(('app_label', 'sales'), ('model__in', ['quote', 'invoice'])), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype', verbose_name='entity type')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='The user who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='The user who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='workflows.workflow', verbose_name='workflow')),
            ],
            options={
                'verbose_name': 'workflow trigger',
                'verbose_name_plural': 'workflow triggers',
                'ordering': ['workflow', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='related entity id')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=10, verbose_name='status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('result_data', models.JSONField(blank=True, default=dict, help_text='Per-action outcomes — see services.run_workflow().', verbose_name='result data')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='error message')),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'crm'), ('model__in', ['customer', 'lead', 'opportunity'])), models.Q(('app_label', 'sales'), ('model__in', ['quote', 'invoice'])), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype', verbose_name='related entity type')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='The user who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='The user who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='workflows.workflow', verbose_name='workflow')),
                ('trigger', models.ForeignKey(blank=True, help_text='Which trigger started this run, if any — null for a manually-invoked run with no matched trigger.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='workflows.workflowtrigger', verbose_name='trigger')),
            ],
            options={
                'verbose_name': 'workflow execution',
                'verbose_name_plural': 'workflow executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['owner'], name='workflows_workflow_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowaction',
            index=models.Index(fields=['workflow', 'position'], name='workflows_action_position_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtrigger',
            index=models.Index(fields=['content_type'], name='workflows_trigger_entity_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['workflow', 'status'], name='workflows_exec_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['content_type', 'object_id'], name='workflows_exec_entity_idx'),
        ),
    ]
