# Generated by Django 5.1.4 on 2026-08-06 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code every entry in this price book is denominated in.', max_length=3, verbose_name='currency')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='The user who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='The user who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'price book',
                'verbose_name_plural': 'price books',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('sku', models.CharField(help_text='Stock keeping unit — a unique catalog identifier.', max_length=64, unique=True, verbose_name='SKU')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='default price')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Business-status flag (e.g. discontinued), independent of soft delete.', verbose_name='is active')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='The user who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='The user who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('code', models.CharField(help_text="A unique catalog identifier (services aren't stocked, so `code`, not `sku`).", max_length=64, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('default_rate', models.DecimalField(decimal_places=2, default=0, help_text='Default billing rate — e.g. per hour or per engagement, unit is not enforced by this model.', max_digits=12, verbose_name='default rate')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='The user who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='The user who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceBookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='price')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Set False by apps.catalog.services.deactivate_pricebook_entry() to retire an entry without deleting it.', verbose_name='is active')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='The user who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('price_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='catalog.pricebook', verbose_name='price book')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='The user who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricebook_entries', to='catalog.product', verbose_name='product')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricebook_entries', to='catalog.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'price book entry',
                'verbose_name_plural': 'price book entries',
                'ordering': ['price_book', 'product', 'service'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='catalog_product_active_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active'], name='catalog_service_active_idx'),
        ),
        migrations.AddIndex(
            model_name='pricebookentry',
            index=models.Index(fields=['price_book', 'is_active'], name='catalog_entry_book_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricebookentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('service__isnull', True)), models.Q(('product__isnull', True), ('service__isnull', False)), _connector='OR'), name='catalog_entry_exactly_one_of_product_or_service'),
        ),
        migrations.AddConstraint(
            model_name='pricebookentry',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('price_book', 'product'), name='catalog_entry_unique_pricebook_product'),
        ),
        migrations.AddConstraint(
            model_name='pricebookentry',
            constraint=models.UniqueConstraint(condition=models.Q(('service__isnull', False)), fields=('price_book', 'service'), name='catalog_entry_unique_pricebook_service'),
        ),
    ]
