# Generated by Django 5.1.4 on 2026-08-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='super_admin_access_code_hash',
            field=models.CharField(blank=True, default='', help_text='Hashed secondary access code required for full SUPER_ADMIN authentication (CP4). Set via set_access_code(), never edited directly. Meaningless for MANAGER/EMPLOYEE users.', max_length=128, verbose_name='Super Admin access code hash'),
        ),
    ]
