# Generated by Django 5.1.4 on 2026-08-05 13:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_super_admin_access_code_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token_jti', models.CharField(help_text="The 'jti' claim of the refresh token this session tracks. Never the token itself.", max_length=255, unique=True, verbose_name='refresh token JTI')),
                ('device_name', models.CharField(blank=True, default='', max_length=255, verbose_name='device name')),
                ('device_type', models.CharField(choices=[('DESKTOP', 'Desktop'), ('MOBILE', 'Mobile'), ('TABLET', 'Tablet'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20, verbose_name='device type')),
                ('browser', models.CharField(blank=True, default='', max_length=100, verbose_name='browser')),
                ('operating_system', models.CharField(blank=True, default='', max_length=100, verbose_name='operating system')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='raw user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last used at')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user session',
                'verbose_name_plural': 'user sessions',
                'ordering': ['-last_used_at'],
                'indexes': [models.Index(fields=['user'], name='accounts_session_user_idx'), models.Index(fields=['refresh_token_jti'], name='accounts_session_jti_idx'), models.Index(fields=['is_active'], name='accounts_session_active_idx'), models.Index(fields=['created_at'], name='accounts_session_created_idx')],
            },
        ),
    ]
