# Generated by Django 5.1.4 on 2026-08-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, default='', help_text='Free-text department/category label for staff management.', max_length=150, verbose_name='department'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default=None, help_text='Display/profile handle shown in staff management. NOT used for authentication — sign-in is always email + password.', max_length=150, null=True, unique=True, verbose_name='username'),
        ),
    ]
