# Generated by Django 5.1.4 on 2026-08-05 19:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('stage', models.CharField(choices=[('NEW', 'New'), ('QUALIFIED', 'Qualified'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], db_index=True, default='NEW', max_length=20, verbose_name='stage')),
                ('value', models.DecimalField(decimal_places=2, default=0, help_text="The deal's monetary value, in this opportunity's own `currency`.", max_digits=14, verbose_name='value')),
                ('probability', models.PositiveSmallIntegerField(default=0, help_text='Estimated likelihood of winning, as a percentage (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='probability')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='expected close date')),
                ('actual_close_date', models.DateField(blank=True, help_text='Set automatically by mark_won()/mark_lost() — see apps.crm.services.', null=True, verbose_name='actual close date')),
                ('currency', models.CharField(default='USD', help_text="ISO 4217 currency code. `value` is stored as a plain decimal with no cross-currency conversion — comparing/aggregating `value` across opportunities with different `currency` values is the caller's responsibility, not something this model attempts to normalize.", max_length=3, verbose_name='currency')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('is_closed', models.BooleanField(db_index=True, default=False, help_text='Set automatically by mark_won()/mark_lost()/reopen() — see apps.crm.services.', verbose_name='is closed')),
                ('is_won', models.BooleanField(db_index=True, default=False, help_text='Set automatically by mark_won()/mark_lost()/reopen() — see apps.crm.services.', verbose_name='is won')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='The user who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='crm.customer', verbose_name='customer')),
                ('owner', models.ForeignKey(blank=True, help_text='The user (typically Manager-or-above) responsible for closing this deal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='The user who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'opportunity',
                'verbose_name_plural': 'opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('activity_type', models.CharField(choices=[('CALL', 'Call'), ('EMAIL', 'Email'), ('MEETING', 'Meeting'), ('TASK', 'Task'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20, verbose_name='activity type')),
                ('subject', models.CharField(max_length=200, verbose_name='subject')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='occurred at')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='The user who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.opportunity', verbose_name='opportunity')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='The user who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'opportunity activity',
                'verbose_name_plural': 'opportunity activities',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('content', models.TextField(verbose_name='content')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='The user who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='crm.opportunity', verbose_name='opportunity')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='The user who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'opportunity note',
                'verbose_name_plural': 'opportunity notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['customer', 'stage'], name='crm_opp_customer_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['owner'], name='crm_opportunity_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['is_closed', 'is_won'], name='crm_opp_closed_won_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['expected_close_date'], name='crm_opp_expected_close_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunityactivity',
            index=models.Index(fields=['opportunity', 'occurred_at'], name='crm_opp_activity_occurred_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunitynote',
            index=models.Index(fields=['opportunity'], name='crm_opportunity_note_opp_idx'),
        ),
    ]
