# Generated by Django 5.1.4 on 2026-08-20 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_lead_crm_lead_email_idx_lead_crm_lead_phone_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='external_source_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text="This lead's own id in whatever external system it came from (e.g. a Facebook Lead Ads leadgen_id, a webhook provider's event id) — NOT this row's own primary key. Lets a future ingestion pathway recognize the same external lead delivered twice (a webhook retry, a re-run sync) as one lead, not two, via the unique constraint below, instead of relying on email/phone matching alone. Blank for a lead entered directly or through the existing import, neither of which has one.", max_length=255, verbose_name='external source id'),
        ),
        migrations.AddField(
            model_name='lead',
            name='received_at',
            field=models.DateTimeField(blank=True, help_text="When this lead actually arrived at its external source, if known and different from `created_at` — e.g. a batch sync ingesting leads hours after they were really submitted. Falls back to `created_at` (this row's own creation time) when not set, which is exactly right for every ingestion path that exists today.", null=True, verbose_name='received at'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source_metadata',
            field=models.JSONField(blank=True, default=dict, help_text="Extra data carried by an external lead source that doesn't warrant its own column — campaign name, ad/form id, UTM parameters, or the provider's own raw payload, for reference. Never read for access control or business logic, and never included in PII masking decisions (`source` above already covers the one source-related field masking applies to).", verbose_name='source metadata'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('external_source_id', ''), _negated=True), fields=('external_source_id',), name='crm_lead_unique_external_source_id'),
        ),
    ]
