# Generated by Django 5.1.4 on 2026-08-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_lead_external_ingestion_readiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('CONVERTED', 'Converted'), ('LOST', 'Lost'), ('DNC', 'DNC'), ('NO_ANSWER', 'No Answer'), ('NOT_INTERESTED', 'Not Interested'), ('CALL_BACK', 'Call Back')], db_index=True, default='NEW', max_length=20, verbose_name='status'),
        ),
    ]
