# Generated by Django 5.1.4 on 2026-08-06 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='The user who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_dashboards', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='The user who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'dashboard',
                'verbose_name_plural': 'dashboards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('report_type', models.CharField(choices=[('PRODUCTIVITY', 'Productivity'), ('LEAD_CONVERSION', 'Lead Conversion'), ('SALES_PIPELINE', 'Sales Pipeline'), ('CUSTOMER_ACTIVITY', 'Customer Activity'), ('CUSTOM', 'Custom')], db_index=True, max_length=20, verbose_name='report type')),
                ('filters', models.JSONField(blank=True, default=dict, help_text="Parameters narrowing this report's computation — e.g. a date range or an owner_id — interpreted by services.execute_report()'s dispatch for this report_type.", verbose_name='filters')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Business-status flag (e.g. retired report), independent of soft delete.', verbose_name='is active')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='The user who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_reports', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='The user who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'saved report',
                'verbose_name_plural': 'saved reports',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=10, verbose_name='status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('result_data', models.JSONField(blank=True, default=dict, verbose_name='result data')),
                ('row_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='row count')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='error message')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='The user who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_executions', to=settings.AUTH_USER_MODEL, verbose_name='executed by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='The user who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='reports.savedreport', verbose_name='report')),
            ],
            options={
                'verbose_name': 'report execution',
                'verbose_name_plural': 'report executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('widget_type', models.CharField(choices=[('CHART', 'Chart'), ('TABLE', 'Table'), ('METRIC', 'Metric')], default='TABLE', max_length=10, verbose_name='widget type')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Widget-specific display config (e.g. chart type, color) — opaque to the backend, interpreted by the frontend.', verbose_name='configuration')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='The user who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='reports.dashboard', verbose_name='dashboard')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='The user who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='reports.savedreport', verbose_name='report')),
            ],
            options={
                'verbose_name': 'dashboard widget',
                'verbose_name_plural': 'dashboard widgets',
                'ordering': ['dashboard', 'position'],
            },
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['owner'], name='reports_dashboard_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='dashboard',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('owner',), name='reports_dashboard_unique_default_per_owner'),
        ),
        migrations.AddIndex(
            model_name='savedreport',
            index=models.Index(fields=['owner'], name='reports_savedreport_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['report', 'status'], name='reports_execution_status_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardwidget',
            index=models.Index(fields=['dashboard', 'position'], name='reports_widget_dash_pos_idx'),
        ),
    ]
