# Generated by Django 5.1.4 on 2026-08-06 06:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='name')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('body', models.TextField(verbose_name='body')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Business-status flag (e.g. retired template), independent of soft delete.', verbose_name='is active')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='The user who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='The user who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'email template',
                'verbose_name_plural': 'email templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='related entity id')),
                ('to_email', models.EmailField(max_length=254, verbose_name='to')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('body', models.TextField(verbose_name='body')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=10, verbose_name='status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='error message')),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'crm'), ('model__in', ['customer', 'lead', 'opportunity'])), models.Q(('app_label', 'sales'), ('model__in', ['quote', 'invoice'])), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype', verbose_name='related entity type')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='The user who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('owner', models.ForeignKey(blank=True, help_text='The user who queued this email — used for ownership-based access scoping.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_email_messages', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='The user who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('template', models.ForeignKey(blank=True, help_text='The template this message was rendered from, if any — purely informational (see subject/body).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='communications.emailtemplate', verbose_name='template')),
            ],
            options={
                'verbose_name': 'email message',
                'verbose_name_plural': 'email messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='related entity id')),
                ('notification_type', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ASSIGNMENT', 'Assignment'), ('REMINDER', 'Reminder'), ('SYSTEM', 'System')], db_index=True, default='INFO', max_length=20, verbose_name='notification type')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('message', models.TextField(blank=True, default='', verbose_name='message')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='is read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'crm'), ('model__in', ['customer', 'lead', 'opportunity'])), models.Q(('app_label', 'sales'), ('model__in', ['quote', 'invoice'])), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype', verbose_name='related entity type')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='The user who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='The user who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='related entity id')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('NOTIFICATION', 'Notification'), ('OTHER', 'Other')], db_index=True, max_length=20, verbose_name='channel')),
                ('summary', models.CharField(max_length=255, verbose_name='summary')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='occurred at')),
                ('actor', models.ForeignKey(blank=True, help_text='The user this communication was sent on behalf of, if known — null for system-triggered entries.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_logs', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'crm'), ('model__in', ['customer', 'lead', 'opportunity'])), models.Q(('app_label', 'sales'), ('model__in', ['quote', 'invoice'])), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype', verbose_name='related entity type')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='The user who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='The user who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'communication log',
                'verbose_name_plural': 'communication logs',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['actor'], name='comms_log_actor_idx'), models.Index(fields=['content_type', 'object_id'], name='comms_log_entity_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['is_active'], name='comms_template_active_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['owner'], name='comms_email_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['status'], name='comms_email_status_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['content_type', 'object_id'], name='comms_email_entity_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='comms_notif_recipient_read_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['content_type', 'object_id'], name='comms_notif_entity_idx'),
        ),
    ]
