# Generated by Django 5.1.4 on 2026-08-15 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('crm', '0003_lead_crm_lead_email_idx_lead_crm_lead_phone_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationlog',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('NOTIFICATION', 'Notification'), ('CALL', 'Call'), ('WHATSAPP', 'WhatsApp'), ('OTHER', 'Other')], db_index=True, max_length=20, verbose_name='channel'),
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='related entity id')),
                ('direction', models.CharField(choices=[('OUTBOUND', 'Outbound'), ('INBOUND', 'Inbound')], max_length=10, verbose_name='direction')),
                ('from_number', models.CharField(max_length=32, verbose_name='from number')),
                ('to_number', models.CharField(max_length=32, verbose_name='to number')),
                ('provider_call_id', models.CharField(blank=True, default='', help_text="A1 Routes' own opaque call identifier — used to match inbound webhook updates to this row.", max_length=128, verbose_name='provider call id')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RINGING', 'Ringing'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('NO_ANSWER', 'No Answer'), ('BUSY', 'Busy')], db_index=True, default='QUEUED', max_length=12, verbose_name='status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='ended at')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='duration seconds')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='error message')),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'crm'), ('model__in', ['customer', 'lead', 'opportunity'])), models.Q(('app_label', 'sales'), ('model__in', ['quote', 'invoice'])), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype', verbose_name='related entity type')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='The user who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('owner', models.ForeignKey(blank=True, help_text='The user who placed (or, for an inbound call, is assigned) this call.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_calls', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='The user who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'call',
                'verbose_name_plural': 'calls',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner'], name='comms_call_owner_idx'), models.Index(fields=['status'], name='comms_call_status_idx'), models.Index(fields=['provider_call_id'], name='comms_call_provider_id_idx'), models.Index(fields=['content_type', 'object_id'], name='comms_call_entity_idx')],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('direction', models.CharField(choices=[('OUTBOUND', 'Outbound'), ('INBOUND', 'Inbound')], max_length=10, verbose_name='direction')),
                ('sender', models.CharField(max_length=32, verbose_name='sender')),
                ('receiver', models.CharField(max_length=32, verbose_name='receiver')),
                ('message', models.TextField(verbose_name='message')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=10, verbose_name='status')),
                ('provider_message_id', models.CharField(blank=True, default='', help_text="WhatsApp Cloud API's own opaque message identifier — used to match inbound webhook status updates to this row.", max_length=128, verbose_name='provider message id')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='error message')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='The user who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='crm.customer', verbose_name='customer')),
                ('owner', models.ForeignKey(blank=True, help_text='The user who sent this message — null for an inbound message with no assignee yet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_whatsapp_messages', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='The user who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'WhatsApp message',
                'verbose_name_plural': 'WhatsApp messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner'], name='comms_wa_owner_idx'), models.Index(fields=['customer'], name='comms_wa_customer_idx'), models.Index(fields=['status'], name='comms_wa_status_idx'), models.Index(fields=['provider_message_id'], name='comms_wa_provider_id_idx')],
            },
        ),
    ]
