# Generated by Django 5.1.4 on 2026-08-17 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_alter_communicationlog_channel_call_whatsappmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='direction',
            field=models.CharField(choices=[('OUTBOUND', 'Outbound'), ('INBOUND', 'Inbound')], db_index=True, default='OUTBOUND', help_text='INBOUND rows are customer replies received through the inbound-email webhook.', max_length=10, verbose_name='direction'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='in_reply_to',
            field=models.ForeignKey(blank=True, help_text='For an INBOUND reply: the outbound message whose Reply-To address it came back on.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='communications.emailmessage', verbose_name='in reply to'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='reply_token',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Opaque, CRM-owned identifier embedded in this message's Reply-To address so a reply routes back to this conversation WITHOUT the employee (or the reply path) ever handling the customer's real address.", max_length=64, verbose_name='reply token'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='to_email',
            field=models.EmailField(help_text="The customer's REAL address — backend-internal only. Never serialized to an Employee (see apps/communications/serializers.py's EmailMessageSerializer.pii_fields).", max_length=254, verbose_name='to'),
        ),
    ]
