# Generated by Django 5.1.4 on 2026-08-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_emailmessage_direction_emailmessage_in_reply_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationlog',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('NOTIFICATION', 'Notification'), ('CALL', 'Call'), ('OTHER', 'Other')], db_index=True, max_length=20, verbose_name='channel'),
        ),
        migrations.DeleteModel(
            name='WhatsAppMessage',
        ),
    ]
