# Generated by Django 5.1.4 on 2026-08-06 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_opportunity_opportunityactivity_opportunitynote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='invoice number')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20, verbose_name='status')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='due date')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='subtotal')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='tax')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='total')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='The user who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='crm.customer', verbose_name='customer')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_invoices', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='The user who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('quote_number', models.CharField(max_length=50, unique=True, verbose_name='quote number')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CONVERTED', 'Converted')], db_index=True, default='DRAFT', max_length=20, verbose_name='status')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='valid until')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='subtotal')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='tax')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='total')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_quotes', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('converted_invoice', models.ForeignKey(blank=True, help_text='Set once this quote has been converted — see apps.sales.services.convert_quote_to_invoice().', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quote', to='sales.invoice', verbose_name='converted invoice')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='The user who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='crm.customer', verbose_name='customer')),
                ('opportunity', models.ForeignKey(blank=True, help_text='The deal this quote was drafted for, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='crm.opportunity', verbose_name='opportunity')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_quotes', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='The user who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'quote',
                'verbose_name_plural': 'quotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='quote',
            field=models.ForeignKey(blank=True, help_text='The quote this invoice was converted from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.quote', verbose_name='quote'),
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('product_name', models.CharField(max_length=200, verbose_name='product name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='unit price')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, help_text='quantity * unit_price — recalculated by apps.sales.services, never hand-edited.', max_digits=14, verbose_name='total price')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='ordering')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='The user who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.quote', verbose_name='quote')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='The user who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'quote item',
                'verbose_name_plural': 'quote items',
                'ordering': ['quote', 'ordering', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('product_name', models.CharField(max_length=200, verbose_name='product name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='unit price')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, help_text='quantity * unit_price — recalculated by apps.sales.services, never hand-edited.', max_digits=14, verbose_name='total price')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='ordering')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='The user who created this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.invoice', verbose_name='invoice')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='The user who last updated this record, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'invoice item',
                'verbose_name_plural': 'invoice items',
                'ordering': ['invoice', 'ordering', 'id'],
                'indexes': [models.Index(fields=['invoice', 'ordering'], name='sales_invoiceitem_order_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['customer', 'status'], name='sales_quote_cust_status_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['owner'], name='sales_quote_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['valid_until'], name='sales_quote_valid_until_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', 'status'], name='sales_invoice_cust_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['owner'], name='sales_invoice_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='sales_invoice_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteitem',
            index=models.Index(fields=['quote', 'ordering'], name='sales_quoteitem_order_idx'),
        ),
    ]
